// Code generated by "enumer -type BookName -trimprefix BookName"; DO NOT EDIT.

package codex

import (
	"fmt"
	"strings"
)

const _BookNameName = "UnspecifiedGenExodLevNumDeutJoshJudgRuth1Sam2Sam1Kgs2Kgs1Chr2ChrEzraNehEsthJobPsProvEcclSongIsaJerLamEzekDanHosJoelAmosObadJonahMicNahHabZephHagZechMalMattMarkLukeJohnActsRom1Cor2CorGalEphPhilCol1Thess2Thess1Tim2TimTitusPhlmHebJas1Pet2Pet1John2John3JohnJudeRev"

var _BookNameIndex = [...]uint16{0, 11, 14, 18, 21, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 71, 75, 78, 80, 84, 88, 92, 95, 98, 101, 105, 108, 111, 115, 119, 123, 128, 131, 134, 137, 141, 144, 148, 151, 155, 159, 163, 167, 171, 174, 178, 182, 185, 188, 192, 195, 201, 207, 211, 215, 220, 224, 227, 230, 234, 238, 243, 248, 253, 257, 260}

const _BookNameLowerName = "unspecifiedgenexodlevnumdeutjoshjudgruth1sam2sam1kgs2kgs1chr2chrezranehesthjobpsprovecclsongisajerlamezekdanhosjoelamosobadjonahmicnahhabzephhagzechmalmattmarklukejohnactsrom1cor2corgalephphilcol1thess2thess1tim2timtitusphlmhebjas1pet2pet1john2john3johnjuderev"

func (i BookName) String() string {
	if i >= BookName(len(_BookNameIndex)-1) {
		return fmt.Sprintf("BookName(%d)", i)
	}
	return _BookNameName[_BookNameIndex[i]:_BookNameIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _BookNameNoOp() {
	var x [1]struct{}
	_ = x[BookNameUnspecified-(0)]
	_ = x[BookNameGen-(1)]
	_ = x[BookNameExod-(2)]
	_ = x[BookNameLev-(3)]
	_ = x[BookNameNum-(4)]
	_ = x[BookNameDeut-(5)]
	_ = x[BookNameJosh-(6)]
	_ = x[BookNameJudg-(7)]
	_ = x[BookNameRuth-(8)]
	_ = x[BookName1Sam-(9)]
	_ = x[BookName2Sam-(10)]
	_ = x[BookName1Kgs-(11)]
	_ = x[BookName2Kgs-(12)]
	_ = x[BookName1Chr-(13)]
	_ = x[BookName2Chr-(14)]
	_ = x[BookNameEzra-(15)]
	_ = x[BookNameNeh-(16)]
	_ = x[BookNameEsth-(17)]
	_ = x[BookNameJob-(18)]
	_ = x[BookNamePs-(19)]
	_ = x[BookNameProv-(20)]
	_ = x[BookNameEccl-(21)]
	_ = x[BookNameSong-(22)]
	_ = x[BookNameIsa-(23)]
	_ = x[BookNameJer-(24)]
	_ = x[BookNameLam-(25)]
	_ = x[BookNameEzek-(26)]
	_ = x[BookNameDan-(27)]
	_ = x[BookNameHos-(28)]
	_ = x[BookNameJoel-(29)]
	_ = x[BookNameAmos-(30)]
	_ = x[BookNameObad-(31)]
	_ = x[BookNameJonah-(32)]
	_ = x[BookNameMic-(33)]
	_ = x[BookNameNah-(34)]
	_ = x[BookNameHab-(35)]
	_ = x[BookNameZeph-(36)]
	_ = x[BookNameHag-(37)]
	_ = x[BookNameZech-(38)]
	_ = x[BookNameMal-(39)]
	_ = x[BookNameMatt-(40)]
	_ = x[BookNameMark-(41)]
	_ = x[BookNameLuke-(42)]
	_ = x[BookNameJohn-(43)]
	_ = x[BookNameActs-(44)]
	_ = x[BookNameRom-(45)]
	_ = x[BookName1Cor-(46)]
	_ = x[BookName2Cor-(47)]
	_ = x[BookNameGal-(48)]
	_ = x[BookNameEph-(49)]
	_ = x[BookNamePhil-(50)]
	_ = x[BookNameCol-(51)]
	_ = x[BookName1Thess-(52)]
	_ = x[BookName2Thess-(53)]
	_ = x[BookName1Tim-(54)]
	_ = x[BookName2Tim-(55)]
	_ = x[BookNameTitus-(56)]
	_ = x[BookNamePhlm-(57)]
	_ = x[BookNameHeb-(58)]
	_ = x[BookNameJas-(59)]
	_ = x[BookName1Pet-(60)]
	_ = x[BookName2Pet-(61)]
	_ = x[BookName1John-(62)]
	_ = x[BookName2John-(63)]
	_ = x[BookName3John-(64)]
	_ = x[BookNameJude-(65)]
	_ = x[BookNameRev-(66)]
}

var _BookNameValues = []BookName{BookNameUnspecified, BookNameGen, BookNameExod, BookNameLev, BookNameNum, BookNameDeut, BookNameJosh, BookNameJudg, BookNameRuth, BookName1Sam, BookName2Sam, BookName1Kgs, BookName2Kgs, BookName1Chr, BookName2Chr, BookNameEzra, BookNameNeh, BookNameEsth, BookNameJob, BookNamePs, BookNameProv, BookNameEccl, BookNameSong, BookNameIsa, BookNameJer, BookNameLam, BookNameEzek, BookNameDan, BookNameHos, BookNameJoel, BookNameAmos, BookNameObad, BookNameJonah, BookNameMic, BookNameNah, BookNameHab, BookNameZeph, BookNameHag, BookNameZech, BookNameMal, BookNameMatt, BookNameMark, BookNameLuke, BookNameJohn, BookNameActs, BookNameRom, BookName1Cor, BookName2Cor, BookNameGal, BookNameEph, BookNamePhil, BookNameCol, BookName1Thess, BookName2Thess, BookName1Tim, BookName2Tim, BookNameTitus, BookNamePhlm, BookNameHeb, BookNameJas, BookName1Pet, BookName2Pet, BookName1John, BookName2John, BookName3John, BookNameJude, BookNameRev}

var _BookNameNameToValueMap = map[string]BookName{
	_BookNameName[0:11]:         BookNameUnspecified,
	_BookNameLowerName[0:11]:    BookNameUnspecified,
	_BookNameName[11:14]:        BookNameGen,
	_BookNameLowerName[11:14]:   BookNameGen,
	_BookNameName[14:18]:        BookNameExod,
	_BookNameLowerName[14:18]:   BookNameExod,
	_BookNameName[18:21]:        BookNameLev,
	_BookNameLowerName[18:21]:   BookNameLev,
	_BookNameName[21:24]:        BookNameNum,
	_BookNameLowerName[21:24]:   BookNameNum,
	_BookNameName[24:28]:        BookNameDeut,
	_BookNameLowerName[24:28]:   BookNameDeut,
	_BookNameName[28:32]:        BookNameJosh,
	_BookNameLowerName[28:32]:   BookNameJosh,
	_BookNameName[32:36]:        BookNameJudg,
	_BookNameLowerName[32:36]:   BookNameJudg,
	_BookNameName[36:40]:        BookNameRuth,
	_BookNameLowerName[36:40]:   BookNameRuth,
	_BookNameName[40:44]:        BookName1Sam,
	_BookNameLowerName[40:44]:   BookName1Sam,
	_BookNameName[44:48]:        BookName2Sam,
	_BookNameLowerName[44:48]:   BookName2Sam,
	_BookNameName[48:52]:        BookName1Kgs,
	_BookNameLowerName[48:52]:   BookName1Kgs,
	_BookNameName[52:56]:        BookName2Kgs,
	_BookNameLowerName[52:56]:   BookName2Kgs,
	_BookNameName[56:60]:        BookName1Chr,
	_BookNameLowerName[56:60]:   BookName1Chr,
	_BookNameName[60:64]:        BookName2Chr,
	_BookNameLowerName[60:64]:   BookName2Chr,
	_BookNameName[64:68]:        BookNameEzra,
	_BookNameLowerName[64:68]:   BookNameEzra,
	_BookNameName[68:71]:        BookNameNeh,
	_BookNameLowerName[68:71]:   BookNameNeh,
	_BookNameName[71:75]:        BookNameEsth,
	_BookNameLowerName[71:75]:   BookNameEsth,
	_BookNameName[75:78]:        BookNameJob,
	_BookNameLowerName[75:78]:   BookNameJob,
	_BookNameName[78:80]:        BookNamePs,
	_BookNameLowerName[78:80]:   BookNamePs,
	_BookNameName[80:84]:        BookNameProv,
	_BookNameLowerName[80:84]:   BookNameProv,
	_BookNameName[84:88]:        BookNameEccl,
	_BookNameLowerName[84:88]:   BookNameEccl,
	_BookNameName[88:92]:        BookNameSong,
	_BookNameLowerName[88:92]:   BookNameSong,
	_BookNameName[92:95]:        BookNameIsa,
	_BookNameLowerName[92:95]:   BookNameIsa,
	_BookNameName[95:98]:        BookNameJer,
	_BookNameLowerName[95:98]:   BookNameJer,
	_BookNameName[98:101]:       BookNameLam,
	_BookNameLowerName[98:101]:  BookNameLam,
	_BookNameName[101:105]:      BookNameEzek,
	_BookNameLowerName[101:105]: BookNameEzek,
	_BookNameName[105:108]:      BookNameDan,
	_BookNameLowerName[105:108]: BookNameDan,
	_BookNameName[108:111]:      BookNameHos,
	_BookNameLowerName[108:111]: BookNameHos,
	_BookNameName[111:115]:      BookNameJoel,
	_BookNameLowerName[111:115]: BookNameJoel,
	_BookNameName[115:119]:      BookNameAmos,
	_BookNameLowerName[115:119]: BookNameAmos,
	_BookNameName[119:123]:      BookNameObad,
	_BookNameLowerName[119:123]: BookNameObad,
	_BookNameName[123:128]:      BookNameJonah,
	_BookNameLowerName[123:128]: BookNameJonah,
	_BookNameName[128:131]:      BookNameMic,
	_BookNameLowerName[128:131]: BookNameMic,
	_BookNameName[131:134]:      BookNameNah,
	_BookNameLowerName[131:134]: BookNameNah,
	_BookNameName[134:137]:      BookNameHab,
	_BookNameLowerName[134:137]: BookNameHab,
	_BookNameName[137:141]:      BookNameZeph,
	_BookNameLowerName[137:141]: BookNameZeph,
	_BookNameName[141:144]:      BookNameHag,
	_BookNameLowerName[141:144]: BookNameHag,
	_BookNameName[144:148]:      BookNameZech,
	_BookNameLowerName[144:148]: BookNameZech,
	_BookNameName[148:151]:      BookNameMal,
	_BookNameLowerName[148:151]: BookNameMal,
	_BookNameName[151:155]:      BookNameMatt,
	_BookNameLowerName[151:155]: BookNameMatt,
	_BookNameName[155:159]:      BookNameMark,
	_BookNameLowerName[155:159]: BookNameMark,
	_BookNameName[159:163]:      BookNameLuke,
	_BookNameLowerName[159:163]: BookNameLuke,
	_BookNameName[163:167]:      BookNameJohn,
	_BookNameLowerName[163:167]: BookNameJohn,
	_BookNameName[167:171]:      BookNameActs,
	_BookNameLowerName[167:171]: BookNameActs,
	_BookNameName[171:174]:      BookNameRom,
	_BookNameLowerName[171:174]: BookNameRom,
	_BookNameName[174:178]:      BookName1Cor,
	_BookNameLowerName[174:178]: BookName1Cor,
	_BookNameName[178:182]:      BookName2Cor,
	_BookNameLowerName[178:182]: BookName2Cor,
	_BookNameName[182:185]:      BookNameGal,
	_BookNameLowerName[182:185]: BookNameGal,
	_BookNameName[185:188]:      BookNameEph,
	_BookNameLowerName[185:188]: BookNameEph,
	_BookNameName[188:192]:      BookNamePhil,
	_BookNameLowerName[188:192]: BookNamePhil,
	_BookNameName[192:195]:      BookNameCol,
	_BookNameLowerName[192:195]: BookNameCol,
	_BookNameName[195:201]:      BookName1Thess,
	_BookNameLowerName[195:201]: BookName1Thess,
	_BookNameName[201:207]:      BookName2Thess,
	_BookNameLowerName[201:207]: BookName2Thess,
	_BookNameName[207:211]:      BookName1Tim,
	_BookNameLowerName[207:211]: BookName1Tim,
	_BookNameName[211:215]:      BookName2Tim,
	_BookNameLowerName[211:215]: BookName2Tim,
	_BookNameName[215:220]:      BookNameTitus,
	_BookNameLowerName[215:220]: BookNameTitus,
	_BookNameName[220:224]:      BookNamePhlm,
	_BookNameLowerName[220:224]: BookNamePhlm,
	_BookNameName[224:227]:      BookNameHeb,
	_BookNameLowerName[224:227]: BookNameHeb,
	_BookNameName[227:230]:      BookNameJas,
	_BookNameLowerName[227:230]: BookNameJas,
	_BookNameName[230:234]:      BookName1Pet,
	_BookNameLowerName[230:234]: BookName1Pet,
	_BookNameName[234:238]:      BookName2Pet,
	_BookNameLowerName[234:238]: BookName2Pet,
	_BookNameName[238:243]:      BookName1John,
	_BookNameLowerName[238:243]: BookName1John,
	_BookNameName[243:248]:      BookName2John,
	_BookNameLowerName[243:248]: BookName2John,
	_BookNameName[248:253]:      BookName3John,
	_BookNameLowerName[248:253]: BookName3John,
	_BookNameName[253:257]:      BookNameJude,
	_BookNameLowerName[253:257]: BookNameJude,
	_BookNameName[257:260]:      BookNameRev,
	_BookNameLowerName[257:260]: BookNameRev,
}

var _BookNameNames = []string{
	_BookNameName[0:11],
	_BookNameName[11:14],
	_BookNameName[14:18],
	_BookNameName[18:21],
	_BookNameName[21:24],
	_BookNameName[24:28],
	_BookNameName[28:32],
	_BookNameName[32:36],
	_BookNameName[36:40],
	_BookNameName[40:44],
	_BookNameName[44:48],
	_BookNameName[48:52],
	_BookNameName[52:56],
	_BookNameName[56:60],
	_BookNameName[60:64],
	_BookNameName[64:68],
	_BookNameName[68:71],
	_BookNameName[71:75],
	_BookNameName[75:78],
	_BookNameName[78:80],
	_BookNameName[80:84],
	_BookNameName[84:88],
	_BookNameName[88:92],
	_BookNameName[92:95],
	_BookNameName[95:98],
	_BookNameName[98:101],
	_BookNameName[101:105],
	_BookNameName[105:108],
	_BookNameName[108:111],
	_BookNameName[111:115],
	_BookNameName[115:119],
	_BookNameName[119:123],
	_BookNameName[123:128],
	_BookNameName[128:131],
	_BookNameName[131:134],
	_BookNameName[134:137],
	_BookNameName[137:141],
	_BookNameName[141:144],
	_BookNameName[144:148],
	_BookNameName[148:151],
	_BookNameName[151:155],
	_BookNameName[155:159],
	_BookNameName[159:163],
	_BookNameName[163:167],
	_BookNameName[167:171],
	_BookNameName[171:174],
	_BookNameName[174:178],
	_BookNameName[178:182],
	_BookNameName[182:185],
	_BookNameName[185:188],
	_BookNameName[188:192],
	_BookNameName[192:195],
	_BookNameName[195:201],
	_BookNameName[201:207],
	_BookNameName[207:211],
	_BookNameName[211:215],
	_BookNameName[215:220],
	_BookNameName[220:224],
	_BookNameName[224:227],
	_BookNameName[227:230],
	_BookNameName[230:234],
	_BookNameName[234:238],
	_BookNameName[238:243],
	_BookNameName[243:248],
	_BookNameName[248:253],
	_BookNameName[253:257],
	_BookNameName[257:260],
}

// BookNameString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func BookNameString(s string) (BookName, error) {
	if val, ok := _BookNameNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _BookNameNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to BookName values", s)
}

// BookNameValues returns all values of the enum
func BookNameValues() []BookName {
	return _BookNameValues
}

// BookNameStrings returns a slice of all String values of the enum
func BookNameStrings() []string {
	strs := make([]string, len(_BookNameNames))
	copy(strs, _BookNameNames)
	return strs
}

// IsABookName returns "true" if the value is listed in the enum definition. "false" otherwise
func (i BookName) IsABookName() bool {
	for _, v := range _BookNameValues {
		if i == v {
			return true
		}
	}
	return false
}
